"""Stage 1 of the project: exploratory analysis of training data.

This script analyzes synthetic strength-training data generated by the
`generator/` module. The goal of this stage is to inspect the dataset structure,
data quality, variable distributions, training trends, and first features for
later modeling.

Analysis outputs, helper tables, and plots are saved to `outputs/eda_outputs`.
The final part contains a baseline regression model and a simple recommendation
prototype. These are not final system components yet; they are a bridge toward
Stage 2: modeling and training recommendations.
"""


# ============================================================
# 1. Dependencies and display settings
# ============================================================

import os
import warnings

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score


warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", 100)
pd.set_option("display.width", 160)

sns.set_theme(style="whitegrid")


# ============================================================
# 2. Analysis configuration
# ============================================================

DATA_PATH = "data/FINAL_ENGINE_V4.csv"
OUTPUT_DIR = "outputs/eda_outputs"

RUN_BASELINE_MODEL = True

# The full dataset can make the baseline slow to train, so we cap the sample size.
# This model is a reference point, not a final production model.
MODEL_SAMPLE_SIZE = 200_000

os.makedirs(OUTPUT_DIR, exist_ok=True)


# ============================================================
# 3. Helper functions
# ============================================================

def display_table(obj, title=None):
    """Display a table in a notebook, or print it in the console otherwise."""
    if title:
        print("\n" + "=" * 100)
        print(title)
        print("=" * 100)

    try:
        display(obj)
    except NameError:
        print(obj)


def save_plot(filename):
    """Save the current plot to the EDA output directory."""
    path = os.path.join(OUTPUT_DIR, filename)
    plt.tight_layout()
    plt.savefig(path, dpi=150, bbox_inches="tight")
    plt.show()


def print_section(title):
    """Print a readable separator for the next analysis section."""
    print("\n" + "#" * 100)
    print(title)
    print("#" * 100)


# ============================================================
# 4. Data loading
# ============================================================

print_section("DATA LOADING")

df = pd.read_csv(DATA_PATH)

print(f"Number of rows: {df.shape[0]:,}")
print(f"Number of columns: {df.shape[1]:,}")

display_table(df.head(), "First 5 rows")


# ============================================================
# 5. Basic dataset structure
# ============================================================

print_section("BASIC DATASET STRUCTURE")

print("Dataset columns:")
print(df.columns.tolist())

display_table(
    pd.DataFrame({
        "column": df.columns,
        "dtype": df.dtypes.astype(str).values
    }),
    "Data types"
)

print("\nDataset info:")
df.info()


# ============================================================
# 6. Dataset schema validation
# ============================================================

print_section("DATASET SCHEMA VALIDATION")

required_columns = [
    "user_id", "session_id", "date",
    "exercise", "set_number", "reps", "weight",
    "fatigue", "rir", "level", "split", "phase", "sex"
]

missing_required_columns = [col for col in required_columns if col not in df.columns]

# Required columns are the contract between the generator, EDA, and modeling.
# Catching schema issues early prevents misleading conclusions later.
if missing_required_columns:
    print("Missing required columns:")
    print(missing_required_columns)
else:
    print("All required columns are present.")

if "age" not in df.columns:
    print("\nNOTE:")
    print("The dataset does not contain an 'age' column.")
    print("If the system should personalize plans by age, age should come from the user intake form")
    print("or from a separate user profile table.")
    # Missing age is a known limitation of the current synthetic data schema.


# ============================================================
# 7. Date preparation
# ============================================================

print_section("DATE PREPARATION")

# Date is needed for trends, weekly aggregations, and progress-over-time analysis.
df["date"] = pd.to_datetime(df["date"], errors="coerce")

print("Date range:")
print("From:", df["date"].min())
print("To:", df["date"].max())
print("Number of days:", (df["date"].max() - df["date"].min()).days + 1)


# ============================================================
# 8. Data quality
# ============================================================

print_section("DATA QUALITY")

missing_count = df.isna().sum().sort_values(ascending=False)
missing_percent = (df.isna().mean() * 100).sort_values(ascending=False)

missing_table = pd.DataFrame({
    "missing_count": missing_count,
    "missing_percent": missing_percent
})

display_table(missing_table, "Missing values")

duplicates_count = df.duplicated().sum()
print(f"Number of duplicates: {duplicates_count:,}")


# ============================================================
# 9. Basic dataset statistics
# ============================================================

print_section("BASIC DATASET STATISTICS")

summary = {
    "record_count": len(df),
    "user_count": df["user_id"].nunique(),
    "session_count": df["session_id"].nunique(),
    "exercise_count": df["exercise"].nunique(),
    "level_count": df["level"].nunique(),
    "split_count": df["split"].nunique(),
    "phase_count": df["phase"].nunique(),
    "sex_count": df["sex"].nunique(),
    "first_date": df["date"].min(),
    "last_date": df["date"].max()
}

summary_df = pd.DataFrame(summary.items(), columns=["metric", "value"])

display_table(summary_df, "Dataset summary")
summary_df.to_csv(os.path.join(OUTPUT_DIR, "summary_dataset.csv"), index=False)


# ============================================================
# 10. Categorical variable analysis
# ============================================================

print_section("CATEGORICAL VARIABLE ANALYSIS")

categorical_cols = ["exercise", "level", "split", "phase", "sex"]

for col in categorical_cols:
    counts = df[col].value_counts().reset_index()
    counts.columns = [col, "count"]

    display_table(counts, f"Distribution of variable: {col}")

    counts.to_csv(
        os.path.join(OUTPUT_DIR, f"value_counts_{col}.csv"),
        index=False
    )


# ============================================================
# 11. Categorical variable visualization
# ============================================================

print_section("CATEGORICAL VARIABLE VISUALIZATION")

for col in ["level", "split", "phase", "sex"]:
    plt.figure(figsize=(8, 4))
    sns.countplot(
        data=df,
        x=col,
        order=df[col].value_counts().index
    )
    plt.title(f"Distribution of variable: {col}")
    plt.xlabel(col)
    plt.ylabel("Number of records")
    plt.xticks(rotation=30)
    save_plot(f"countplot_{col}.png")


# ============================================================
# 12. Exercise analysis
# ============================================================

print_section("EXERCISE ANALYSIS")

exercise_counts = df["exercise"].value_counts()

plt.figure(figsize=(12, 7))
sns.barplot(
    x=exercise_counts.values,
    y=exercise_counts.index
)
plt.title("Most frequent exercises")
plt.xlabel("Number of records")
plt.ylabel("Exercise")
save_plot("exercise_counts.png")

exercise_counts_df = exercise_counts.reset_index()
exercise_counts_df.columns = ["exercise", "count"]

display_table(exercise_counts_df, "Exercise frequency")
exercise_counts_df.to_csv(os.path.join(OUTPUT_DIR, "exercise_counts.csv"), index=False)


# ============================================================
# 13. Numeric variable analysis
# ============================================================

print_section("NUMERIC VARIABLE ANALYSIS")

numeric_cols = ["set_number", "reps", "weight", "fatigue", "rir"]

numeric_description = df[numeric_cols].describe(
    percentiles=[0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99]
).T

display_table(numeric_description, "Descriptive statistics for numeric variables")
numeric_description.to_csv(os.path.join(OUTPUT_DIR, "numeric_description.csv"))


# ============================================================
# 14. Numeric variable distributions
# ============================================================

print_section("NUMERIC VARIABLE DISTRIBUTIONS")

for col in numeric_cols:
    plt.figure(figsize=(9, 4))
    sns.histplot(df[col], bins=50, kde=True)
    plt.title(f"Distribution of variable: {col}")
    plt.xlabel(col)
    plt.ylabel("Number of observations")
    save_plot(f"hist_{col}.png")


# ============================================================
# 15. Outliers
# ============================================================

print_section("OUTLIERS")

for col in ["reps", "weight", "fatigue", "rir"]:
    plt.figure(figsize=(9, 4))
    sns.boxplot(data=df, x=col)
    plt.title(f"Boxplot for variable: {col}")
    plt.xlabel(col)
    save_plot(f"boxplot_{col}.png")


# ============================================================
# 16. Feature engineering
# ============================================================

print_section("FEATURE ENGINEERING")

# volume is a simple, readable measure of single-set training load.
df["volume"] = df["reps"] * df["weight"]

# Epley e1RM approximates strength from load and repetitions.
# It is an analytical indicator, not a direct measurement of true max strength.
df["e1rm_epley"] = df["weight"] * (1 + df["reps"] / 30)

display_table(
    df[["exercise", "reps", "weight", "volume", "e1rm_epley"]].head(),
    "New features: volume and e1RM"
)


# ============================================================
# 17. Numeric variable correlation
# ============================================================

print_section("NUMERIC VARIABLE CORRELATION")

corr_cols = [
    "set_number",
    "reps",
    "weight",
    "fatigue",
    "rir",
    "volume",
    "e1rm_epley"
]

corr = df[corr_cols].corr()

plt.figure(figsize=(10, 7))
sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm")
plt.title("Correlation matrix of numeric variables")
save_plot("correlation_heatmap.png")

display_table(corr, "Correlation matrix")
corr.to_csv(os.path.join(OUTPUT_DIR, "correlation_matrix.csv"))


# ============================================================
# 18. Session-level aggregation
# ============================================================

print_section("SESSION-LEVEL AGGREGATION")

# Aggregating into session_df lets us analyze full workouts, not only individual sets.
session_df = (
    df
    .groupby(["user_id", "session_id", "date", "sex", "level", "split", "phase"], as_index=False)
    .agg(
        session_sets=("set_number", "count"),
        session_exercises=("exercise", "nunique"),
        session_volume=("volume", "sum"),
        mean_reps=("reps", "mean"),
        mean_weight=("weight", "mean"),
        mean_fatigue=("fatigue", "mean"),
        mean_rir=("rir", "mean"),
        max_e1rm=("e1rm_epley", "max")
    )
)

print(f"Number of sessions after aggregation: {session_df.shape[0]:,}")

display_table(session_df.head(), "Sample session-level data")
session_df.to_csv(os.path.join(OUTPUT_DIR, "session_level_dataset.csv"), index=False)


# ============================================================
# 19. Training session statistics
# ============================================================

print_section("TRAINING SESSION STATISTICS")

session_numeric_cols = [
    "session_sets",
    "session_exercises",
    "session_volume",
    "mean_reps",
    "mean_weight",
    "mean_fatigue",
    "mean_rir",
    "max_e1rm"
]

session_description = session_df[session_numeric_cols].describe(
    percentiles=[0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99]
).T

display_table(session_description, "Descriptive session statistics")
session_description.to_csv(os.path.join(OUTPUT_DIR, "session_description.csv"))


# ============================================================
# 20. User and session analysis
# ============================================================

print_section("USER AND SESSION ANALYSIS")

sessions_per_user = session_df.groupby("user_id")["session_id"].nunique()

plt.figure(figsize=(10, 5))
sns.histplot(sessions_per_user, bins=30, kde=True)
plt.title("Distribution of sessions per user")
plt.xlabel("Number of sessions")
plt.ylabel("Number of users")
save_plot("sessions_per_user.png")

display_table(sessions_per_user.describe(), "Sessions per user summary")


# ============================================================
# 21. Training frequency
# ============================================================

print_section("TRAINING FREQUENCY")

session_df["week"] = session_df["date"].dt.to_period("W").astype(str)

sessions_per_week = (
    session_df
    .groupby(["user_id", "week"])
    .size()
    .reset_index(name="sessions_per_week")
)

plt.figure(figsize=(8, 4))
sns.histplot(sessions_per_week["sessions_per_week"], bins=10)
plt.title("Weekly training sessions")
plt.xlabel("Sessions per week")
plt.ylabel("Number of observations")
save_plot("sessions_per_week.png")

display_table(
    sessions_per_week["sessions_per_week"].describe(),
    "Weekly sessions summary"
)


# ============================================================
# 22. Training level analysis
# ============================================================

print_section("TRAINING LEVEL ANALYSIS")

level_summary = (
    session_df
    .groupby("level")
    .agg(
        sessions=("session_id", "count"),
        users=("user_id", "nunique"),
        avg_sets=("session_sets", "mean"),
        avg_exercises=("session_exercises", "mean"),
        avg_session_volume=("session_volume", "mean"),
        median_session_volume=("session_volume", "median"),
        avg_fatigue=("mean_fatigue", "mean"),
        avg_rir=("mean_rir", "mean"),
        avg_e1rm=("max_e1rm", "mean")
    )
    .sort_values("avg_session_volume", ascending=False)
)

display_table(level_summary, "Summary by training level")
level_summary.to_csv(os.path.join(OUTPUT_DIR, "level_summary.csv"))

plt.figure(figsize=(8, 4))
sns.barplot(
    data=level_summary.reset_index(),
    x="level",
    y="avg_session_volume"
)
plt.title("Average session volume by training level")
plt.xlabel("Level")
plt.ylabel("Average session volume")
save_plot("avg_volume_by_level.png")


# ============================================================
# 23. Training phase analysis
# ============================================================

print_section("TRAINING PHASE ANALYSIS")

phase_summary = (
    session_df
    .groupby("phase")
    .agg(
        sessions=("session_id", "count"),
        users=("user_id", "nunique"),
        avg_sets=("session_sets", "mean"),
        avg_exercises=("session_exercises", "mean"),
        avg_session_volume=("session_volume", "mean"),
        median_session_volume=("session_volume", "median"),
        avg_fatigue=("mean_fatigue", "mean"),
        avg_rir=("mean_rir", "mean"),
        avg_e1rm=("max_e1rm", "mean")
    )
    .sort_values("avg_session_volume", ascending=False)
)

display_table(phase_summary, "Summary by training phase")
phase_summary.to_csv(os.path.join(OUTPUT_DIR, "phase_summary.csv"))

plt.figure(figsize=(8, 4))
sns.barplot(
    data=phase_summary.reset_index(),
    x="phase",
    y="avg_session_volume"
)
plt.title("Average session volume by training phase")
plt.xlabel("Phase")
plt.ylabel("Average session volume")
save_plot("avg_volume_by_phase.png")


# ============================================================
# 24. Training split analysis
# ============================================================

print_section("TRAINING SPLIT ANALYSIS")

split_summary = (
    session_df
    .groupby("split")
    .agg(
        sessions=("session_id", "count"),
        users=("user_id", "nunique"),
        avg_sets=("session_sets", "mean"),
        avg_exercises=("session_exercises", "mean"),
        avg_session_volume=("session_volume", "mean"),
        median_session_volume=("session_volume", "median"),
        avg_fatigue=("mean_fatigue", "mean"),
        avg_rir=("mean_rir", "mean"),
        avg_e1rm=("max_e1rm", "mean")
    )
    .sort_values("avg_session_volume", ascending=False)
)

display_table(split_summary, "Summary by split")
split_summary.to_csv(os.path.join(OUTPUT_DIR, "split_summary.csv"))

plt.figure(figsize=(8, 4))
sns.barplot(
    data=split_summary.reset_index(),
    x="split",
    y="avg_session_volume"
)
plt.title("Average session volume by split")
plt.xlabel("Split")
plt.ylabel("Average session volume")
save_plot("avg_volume_by_split.png")


# ============================================================
# 25. Sex and training level analysis
# ============================================================

print_section("SEX AND TRAINING LEVEL ANALYSIS")

sex_level_summary = (
    session_df
    .groupby(["sex", "level"])
    .agg(
        sessions=("session_id", "count"),
        users=("user_id", "nunique"),
        avg_session_volume=("session_volume", "mean"),
        median_session_volume=("session_volume", "median"),
        avg_sets=("session_sets", "mean"),
        avg_exercises=("session_exercises", "mean"),
        avg_fatigue=("mean_fatigue", "mean"),
        avg_rir=("mean_rir", "mean"),
        avg_e1rm=("max_e1rm", "mean")
    )
    .reset_index()
)

display_table(sex_level_summary, "Summary by sex and training level")
sex_level_summary.to_csv(os.path.join(OUTPUT_DIR, "sex_level_summary.csv"), index=False)

plt.figure(figsize=(10, 5))
sns.barplot(
    data=sex_level_summary,
    x="level",
    y="avg_session_volume",
    hue="sex"
)
plt.title("Average session volume by sex and training level")
plt.xlabel("Level")
plt.ylabel("Average session volume")
save_plot("avg_volume_by_sex_and_level.png")


# ============================================================
# 26. Exercise characteristics
# ============================================================

print_section("EXERCISE CHARACTERISTICS")

exercise_summary = (
    df
    .groupby("exercise")
    .agg(
        records=("exercise", "size"),
        users=("user_id", "nunique"),
        sessions=("session_id", "nunique"),
        mean_reps=("reps", "mean"),
        median_reps=("reps", "median"),
        mean_weight=("weight", "mean"),
        median_weight=("weight", "median"),
        mean_volume=("volume", "mean"),
        median_volume=("volume", "median"),
        mean_rir=("rir", "mean"),
        mean_fatigue=("fatigue", "mean"),
        mean_e1rm=("e1rm_epley", "mean"),
        median_e1rm=("e1rm_epley", "median")
    )
    .sort_values("records", ascending=False)
)

display_table(exercise_summary, "Exercise summary")
exercise_summary.to_csv(os.path.join(OUTPUT_DIR, "exercise_summary.csv"))


# ============================================================
# 27. Exercise and training level relationship
# ============================================================

print_section("EXERCISE AND TRAINING LEVEL RELATIONSHIP")

exercise_level = pd.crosstab(df["exercise"], df["level"])

plt.figure(figsize=(10, 8))
sns.heatmap(exercise_level, annot=True, fmt="d", cmap="Blues")
plt.title("Record count: exercise vs training level")
plt.xlabel("Level")
plt.ylabel("Exercise")
save_plot("heatmap_exercise_level.png")

display_table(exercise_level, "Exercise vs training level")
exercise_level.to_csv(os.path.join(OUTPUT_DIR, "exercise_level_crosstab.csv"))


# ============================================================
# 28. Split and training phase relationship
# ============================================================

split_phase = pd.crosstab(df["split"], df["phase"])

print_section("SPLIT AND TRAINING PHASE RELATIONSHIP")

plt.figure(figsize=(8, 5))
sns.heatmap(split_phase, annot=True, fmt="d", cmap="Greens")
plt.title("Split vs training phase")
plt.xlabel("Phase")
plt.ylabel("Split")
save_plot("heatmap_split_phase.png")

display_table(split_phase, "Split vs training phase")
split_phase.to_csv(os.path.join(OUTPUT_DIR, "split_phase_crosstab.csv"))


# ============================================================
# 29. Time trends
# ============================================================

print_section("TIME TRENDS")

daily_volume = (
    df
    .groupby("date", as_index=False)
    .agg(total_volume=("volume", "sum"))
    .sort_values("date")
)

daily_volume["rolling_14d_volume"] = daily_volume["total_volume"].rolling(14).mean()
daily_volume["rolling_30d_volume"] = daily_volume["total_volume"].rolling(30).mean()

plt.figure(figsize=(14, 5))
plt.plot(
    daily_volume["date"],
    daily_volume["total_volume"],
    alpha=0.25,
    label="Daily volume"
)
plt.plot(
    daily_volume["date"],
    daily_volume["rolling_14d_volume"],
    label="14-day rolling average"
)
plt.plot(
    daily_volume["date"],
    daily_volume["rolling_30d_volume"],
    label="30-day rolling average"
)
plt.title("Total training volume trend over time")
plt.xlabel("Date")
plt.ylabel("Training volume")
plt.legend()
save_plot("daily_volume_trend.png")

daily_volume.to_csv(os.path.join(OUTPUT_DIR, "daily_volume.csv"), index=False)


# ============================================================
# 30. Example user progression
# ============================================================

print_section("EXAMPLE USER PROGRESSION")

example_user = df["user_id"].value_counts().index[0]

if "Bench Press" in df["exercise"].unique():
    example_exercise = "Bench Press"
else:
    example_exercise = df["exercise"].value_counts().index[0]

progress_df = (
    df[
        (df["user_id"] == example_user) &
        (df["exercise"] == example_exercise)
    ]
    .groupby("date", as_index=False)
    .agg(
        max_weight=("weight", "max"),
        max_e1rm=("e1rm_epley", "max"),
        mean_rir=("rir", "mean"),
        mean_fatigue=("fatigue", "mean"),
        total_volume=("volume", "sum")
    )
    .sort_values("date")
)

display_table(
    progress_df.head(),
    f"Progression for user {example_user} - {example_exercise}"
)

if len(progress_df) > 0:
    plt.figure(figsize=(14, 5))
    plt.plot(progress_df["date"], progress_df["max_weight"], label="Max weight")
    plt.plot(progress_df["date"], progress_df["max_e1rm"], label="Estimated e1RM")
    plt.title(f"Progression for user {example_user} - {example_exercise}")
    plt.xlabel("Date")
    plt.ylabel("Weight / e1RM")
    plt.legend()
    save_plot("example_user_progression_weight_e1rm.png")

    plt.figure(figsize=(14, 5))
    plt.plot(progress_df["date"], progress_df["mean_rir"], label="Mean RIR")
    plt.plot(progress_df["date"], progress_df["mean_fatigue"], label="Mean fatigue")
    plt.title(f"RIR and fatigue for user {example_user} - {example_exercise}")
    plt.xlabel("Date")
    plt.ylabel("Value")
    plt.legend()
    save_plot("example_user_progression_rir_fatigue.png")


# ============================================================
# 31. Baseline ML data preparation
# ============================================================

print_section("BASELINE ML DATA PREPARATION")

model_df = (
    df
    .sort_values(["user_id", "exercise", "date", "session_id", "set_number"])
    .copy()
)

# Historical features use only earlier sets. shift(1) limits data leakage because
# the model cannot see information from the set currently being predicted.
model_df["prev_weight"] = model_df.groupby(["user_id", "exercise"])["weight"].shift(1)
model_df["prev_reps"] = model_df.groupby(["user_id", "exercise"])["reps"].shift(1)
model_df["prev_rir"] = model_df.groupby(["user_id", "exercise"])["rir"].shift(1)
model_df["prev_fatigue"] = model_df.groupby(["user_id", "exercise"])["fatigue"].shift(1)
model_df["prev_volume"] = model_df.groupby(["user_id", "exercise"])["volume"].shift(1)

model_df["rolling_weight_3"] = (
    model_df
    .groupby(["user_id", "exercise"])["weight"]
    .transform(lambda x: x.shift(1).rolling(3).mean())
)

model_df["rolling_reps_3"] = (
    model_df
    .groupby(["user_id", "exercise"])["reps"]
    .transform(lambda x: x.shift(1).rolling(3).mean())
)

model_df["rolling_volume_3"] = (
    model_df
    .groupby(["user_id", "exercise"])["volume"]
    .transform(lambda x: x.shift(1).rolling(3).mean())
)

model_df["rolling_fatigue_3"] = (
    model_df
    .groupby(["user_id", "exercise"])["fatigue"]
    .transform(lambda x: x.shift(1).rolling(3).mean())
)

model_df["rolling_rir_3"] = (
    model_df
    .groupby(["user_id", "exercise"])["rir"]
    .transform(lambda x: x.shift(1).rolling(3).mean())
)

eda_model_ready = model_df.dropna().copy()

print(f"Number of records after historical feature creation: {eda_model_ready.shape[0]:,}")

display_table(
    eda_model_ready[
        [
            "user_id", "exercise", "date", "set_number",
            "prev_weight", "prev_reps", "prev_rir", "prev_fatigue",
            "rolling_weight_3", "rolling_reps_3", "rolling_volume_3",
            "weight"
        ]
    ].head(),
    "Model-ready data"
)

eda_model_ready.to_csv(os.path.join(OUTPUT_DIR, "model_ready_dataset_sample.csv"), index=False)


# ============================================================
# 32. Baseline regression
# ============================================================

if RUN_BASELINE_MODEL:

    print_section("BASELINE REGRESSION MODEL")

    # Sampling keeps the baseline quick to train without changing its role:
    # it provides a reference point before the proper modeling stage.
    if len(eda_model_ready) > MODEL_SAMPLE_SIZE:
        model_sample = eda_model_ready.sample(
            n=MODEL_SAMPLE_SIZE,
            random_state=42
        ).copy()
        print(f"Model sample used: {MODEL_SAMPLE_SIZE:,} records.")
    else:
        model_sample = eda_model_ready.copy()
        print(f"Full dataset used for the model: {len(model_sample):,} records.")

    features = [
        "exercise",
        "level",
        "split",
        "phase",
        "sex",
        "set_number",
        "reps",
        "fatigue",
        "rir",
        "prev_weight",
        "prev_reps",
        "prev_rir",
        "prev_fatigue",
        "prev_volume",
        "rolling_weight_3",
        "rolling_reps_3",
        "rolling_volume_3",
        "rolling_fatigue_3",
        "rolling_rir_3"
    ]

    target = "weight"

    X = model_sample[features]
    y = model_sample[target]

    categorical_features = [
        "exercise",
        "level",
        "split",
        "phase",
        "sex"
    ]

    numeric_features = [
        "set_number",
        "reps",
        "fatigue",
        "rir",
        "prev_weight",
        "prev_reps",
        "prev_rir",
        "prev_fatigue",
        "prev_volume",
        "rolling_weight_3",
        "rolling_reps_3",
        "rolling_volume_3",
        "rolling_fatigue_3",
        "rolling_rir_3"
    ]

    preprocessor = ColumnTransformer(
        transformers=[
            ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features),
            ("num", "passthrough", numeric_features)
        ]
    )

    model = RandomForestRegressor(
        n_estimators=100,
        random_state=42,
        n_jobs=-1,
        max_depth=14,
        min_samples_leaf=3
    )

    pipeline = Pipeline(
        steps=[
            ("preprocessor", preprocessor),
            ("model", model)
        ]
    )

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.2,
        random_state=42
    )

    pipeline.fit(X_train, y_train)

    y_pred = pipeline.predict(X_test)

    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    r2 = r2_score(y_test, y_pred)

    model_results = pd.DataFrame({
        "metric": ["MAE", "RMSE", "R2"],
        "value": [mae, rmse, r2]
    })

    display_table(model_results, "Baseline regression model results")

    model_results.to_csv(
        os.path.join(OUTPUT_DIR, "baseline_model_results.csv"),
        index=False
    )

    # Comparing actual and predicted values shows the model error scale.
    prediction_sample = pd.DataFrame({
        "actual_weight": y_test.values,
        "predicted_weight": y_pred
    })

    prediction_sample["error"] = prediction_sample["actual_weight"] - prediction_sample["predicted_weight"]
    prediction_sample["absolute_error"] = prediction_sample["error"].abs()

    display_table(
        prediction_sample.head(20),
        "Sample model predictions"
    )

    prediction_sample.to_csv(
        os.path.join(OUTPUT_DIR, "baseline_predictions.csv"),
        index=False
    )

    plt.figure(figsize=(7, 7))
    sns.scatterplot(
        x=prediction_sample["actual_weight"],
        y=prediction_sample["predicted_weight"],
        alpha=0.3
    )
    plt.title("Actual vs predicted weight")
    plt.xlabel("Actual weight")
    plt.ylabel("Predicted weight")
    save_plot("actual_vs_predicted_weight.png")

    plt.figure(figsize=(9, 4))
    sns.histplot(prediction_sample["error"], bins=50, kde=True)
    plt.title("Prediction error distribution")
    plt.xlabel("Error: actual - predicted")
    plt.ylabel("Number of observations")
    save_plot("prediction_error_distribution.png")


# ============================================================
# 33. Recommendation prototype
# ============================================================

print_section("TRAINING PLAN RECOMMENDATION PROTOTYPE")

def recommend_training_template(sex, level, goal_phase="hypertrophy"):
    """Build a simple recommendation from similar training records.

    This prototype shows the direction for Stage 2, not the final recommender.
    """

    similar = df[
        (df["sex"] == sex) &
        (df["level"] == level) &
        (df["phase"] == goal_phase)
    ].copy()

    if len(similar) == 0:
        print("No perfectly similar users found. Falling back to level and phase only.")
        similar = df[
            (df["level"] == level) &
            (df["phase"] == goal_phase)
        ].copy()

    if len(similar) == 0:
        print("No data for the selected criteria. Falling back to training level only.")
        similar = df[df["level"] == level].copy()

    if len(similar) == 0:
        print("No data for the selected level. Falling back to the full dataset.")
        similar = df.copy()

    recommended_split = similar["split"].mode()[0]

    top_exercises = (
        similar["exercise"]
        .value_counts()
        .head(6)
        .index
        .tolist()
    )

    params = (
        similar[similar["exercise"].isin(top_exercises)]
        .groupby("exercise")
        .agg(
            recommended_sets=("set_number", "max"),
            avg_reps=("reps", "mean"),
            median_reps=("reps", "median"),
            avg_weight=("weight", "mean"),
            median_weight=("weight", "median"),
            avg_rir=("rir", "mean"),
            avg_fatigue=("fatigue", "mean")
        )
        .reset_index()
    )

    params["recommended_reps"] = params["median_reps"].round().astype(int)
    params["recommended_weight"] = params["median_weight"].round(1)

    result = params[
        [
            "exercise",
            "recommended_sets",
            "recommended_reps",
            "recommended_weight",
            "avg_rir",
            "avg_fatigue"
        ]
    ].copy()

    result.insert(0, "recommended_split", recommended_split)

    return result


# This example shows the recommender output format. It is still a rule-based
# prototype that should be combined with the regression model in the next stage.

example_sex = df["sex"].mode()[0]
example_level = df["level"].mode()[0]
example_phase = "hypertrophy" if "hypertrophy" in df["phase"].unique() else df["phase"].mode()[0]

recommendation = recommend_training_template(
    sex=example_sex,
    level=example_level,
    goal_phase=example_phase
)

display_table(
    recommendation,
    f"Sample plan recommendation for: sex={example_sex}, level={example_level}, phase={example_phase}"
)

recommendation.to_csv(
    os.path.join(OUTPUT_DIR, "example_training_recommendation.csv"),
    index=False
)


# ============================================================
# 34. Final conclusions
# ============================================================

print_section("FINAL CONCLUSION")

print("""
Based on the exploratory data analysis, the dataset is suitable for building an
AI-assisted system for training analysis and training plan recommendation.

Main elements completed in this analysis:
1. Data quality, missing values, and duplicates were checked.
2. Numeric and categorical variable distributions were analyzed.
3. Derived features were created: volume and e1RM.
4. Data was aggregated to the training-session level.
5. Training behavior was compared by level, sex, split, and phase.
6. Data was prepared for a future regression model.
7. A baseline model for predicting training weight was built.
8. A simple training plan recommendation prototype was prepared.

Recommended project direction:
A hybrid recommendation system for generating training plans, supported by a
regression model that predicts suggested training weight.

Limitation:
The dataset does not contain user age. Age should be added as a separate feature
collected in the user intake form or stored in a separate user profile table.
""")

print(f"\nAll output files, plots, and tables were saved in: {OUTPUT_DIR}")
